apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubepilot.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kubepilot.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
